name: Bot Scheduler

on:
  schedule:
    - cron: "0 13 * * *"  # 9 AM UTC (Eastern Time gym opens)
    - cron: "0 3 * * *"   # 11 PM UTC (Eastern Time gym closes)
  workflow_dispatch:       # allows manual triggering from GitHub UI

jobs:
  toggle-active:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          export PATH="$HOME/.railway/bin:$PATH"

      - name: Set ACTIVE and Redeploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          export PATH="$HOME/.railway/bin:$PATH"

          # Decide what value to set based on the scheduled time
          if [ "${{ github.event.schedule }}" == "0 13 * * *" ]; then
            echo "Setting ACTIVE=True"
            railway variables add ACTIVE=True
          else
            echo "Setting ACTIVE=False"
            railway variables add ACTIVE=False
          fi

          # Redeploy the project to apply changes
          railway up --yes
