name: Bot Scheduler

on:
  schedule:
    - cron: "0 13 * * *"  # 9 AM UTC
    - cron: "0 3 * * *"   # 11 PM UTC
  workflow_dispatch:       # lets you trigger it manually too

jobs:
  toggle-active:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          export PATH="$HOME/.railway/bin:$PATH"

      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login --token $RAILWAY_TOKEN

      - name: Set ACTIVE and Redeploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          if [ "${{ github.event.schedule }}" == "0 13 * * *" ]; then
            echo "Setting ACTIVE=True"
            railway variables set ACTIVE True
          else
            echo "Setting ACTIVE=False"
            railway variables set ACTIVE False
          fi

          railway up --yes
